# Generated by Django 3.2.8 on 2022-04-21 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_commentreplay'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentreplay',
            old_name='comment',
            new_name='comment_re',
        ),
    ]
